version: "3"
services:
  filliere-tt:
    command:
    - |
       npm run build
       npm run start
  filliere-tt-strapi:
    command:
    - |
       npm run build
       npm run start
    env_file:
      - ./back/.env.production.local
  filliere-tt-strapi-db:
    env_file:
      - ./back/.env.production.local
