version: "3"
services:
  filliere-tt:
    build:
      context: ./front
    ports:
      - "3000:3000"
  filliere-tt-strapi:
    build:
      context: ./back
    restart: unless-stopped
    ports:
      - "1337:1337"
    depends_on:
      - filliere-tt-strapi-db
  filliere-tt-strapi-db:
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:12.0-alpine
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - "5432:5432"

volumes:
  strapi-data:
