services:
  filliere-tt:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - filliere-tt-strapi
  filliere-tt-strapi:
    build:
      context: ./back
    restart: unless-stopped
    ports:
      - "1337:1337"
    depends_on:
      - filliere-tt-strapi-db
    volumes:
      - ./back/public/uploads:/usr/src/app/public/uploads #using a volume
  filliere-tt-strapi-db:
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - strapi-data-pg16:/var/lib/postgresql/data/ #using a volume

volumes:
  strapi-data-pg16:
