services:
  filliere-tt:
    command:
    - |
       npm run dev
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  filliere-tt-strapi:
    command:
    - |
       npm run develop
    env_file:
      - ./back/.env.development.local
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
  filliere-tt-strapi-db:
    env_file:
      - ./back/.env.development.local
