name: Deploy on push to main

on:
  push:
    branches:
      - main

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y openssh-client expect

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

      - name: Set up SSH agent and run commands
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
        run: |
          # Start the SSH agent
          eval "$(ssh-agent -a $SSH_AUTH_SOCK)"

          # Create the SSH_ASKPASS helper file
          echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass
          chmod +x ~/.ssh_askpass

          # Add the private key to the SSH agent
          DISPLAY=:0 SSH_ASKPASS=~/.ssh_askpass ssh-add /tmp/ssh_key

          # Run SSH commands
          ssh -o StrictHostKeyChecking=no $SSH_SERVER << 'EOF'
            cd /var/filliere-tt
            docker compose stop
            git clean -fd
            git reset --hard
            git pull
            chmod +x /var/filliere-tt/prod/docker_cleanup.sh
            chmod +x /var/filliere-tt/prod/check_disk_space.sh
            chmod +x /var/filliere-tt/prod/check_services.sh
            ls
            docker rm filliere-tt-filliere-tt-1 filliere-tt-filliere-tt-strapi-1 
            docker rmi filliere-tt-filliere-tt filliere-tt-filliere-tt-strapi
            docker compose build --no-cache
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
            exit
          EOF
